---
output:
  html_document:
    css: styles.css
params:
  orcid.id: "0000-0002-9583-8636"
  years.since: 2010
  spacer: ', '
  journal.only: "No"
  order: "dyear"
  max.authors: 3
  style: "APA"
  bullets: 'numbers'
  extra.order: 'None' # alternative is 'ARC' style
  flag.OA: FALSE
  bold.author: FALSE
---

```{r setup, include=FALSE}
library(cvR)
library(scholar)
library(rorcid)
library(kableExtra)
x  <- "dc7ea3ae-38fd-4188-8bd1-1db4215ea139"
Sys.setenv(ORCID_TOKEN=x, orcid_email="aaron.conway@utoronto.ca")
knitr::opts_chunk$set(echo = FALSE, warnings=FALSE, comment='')
```

# Aaron Conway RN PhD

----

>  RBC Chair in Cardiovascular Nursing Research | Peter Munk Cardiac Centre<br>Assistant Professor | Lawrence S. Bloomberg Faculty of Nursing | University of Toronto<br>aaron.conway@utoronto.ca


----

  
## Education

```{r}
edu <- rorcid::orcid_educations(params$orcid.id)
edu <- edu$`0000-0002-9583-8636`$`education-summary` %>% 
  janitor::clean_names() %>% 
  mutate(end_date = tidyr::replace_na(`end_date_year_value`, "Current")) %>%
  mutate(timeframe = glue::glue("{start_date_year_value} - {end_date}")) %>% 
    mutate(location = glue::glue("{organization_address_city}, {organization_address_country}")) %>% 
  select(role_title, organization_name, location, timeframe)

kable(edu, col.names = c("", "", "", ""))%>% 
    kable_styling(bootstrap_options = "hover")
```

## Employment

```{r}
employ <- rorcid::orcid_employments(params$orcid.id)
employ <- employ$`0000-0002-9583-8636`$`employment-summary` %>% 
  janitor::clean_names() %>% 
  mutate(end_date = tidyr::replace_na(`end_date_year_value`, "Current")) %>%
  mutate(timeframe = glue::glue("{start_date_year_value} - {end_date}")) %>% 
    mutate(location = glue::glue("{organization_address_city}, {organization_address_country}")) %>% 
  select(role_title, organization_name, location, timeframe)
kable(employ,  col.names = c("", "", "", ""))%>% 
      column_spec(1, width = "18em") %>% 
    column_spec(2, width = "18em") %>% 
    kable_styling(bootstrap_options = "hover") 
```

## Funding


```{r}
funding <- rorcid::orcid_fundings(params$orcid.id)
pcodes <- vapply(funding[[1]]$group$`funding-summary`, "[[", 1, "put-code")
out <- lapply(pcodes, function(z) orcid_fundings(params$orcid.id, put_code=z))
amount <- vapply(out, function(w) w[[1]]$amount$value, "")
amount  <- paste("$", amount, sep = "")
funding <- funding$`0000-0002-9583-8636`$group$`funding-summary` 
funding <- tibble(
  type = purrr::map_chr(funding, "type"),
  funder = purrr::map_chr(funding, "organization.name"),
  title = purrr::map_chr(funding, "title.title.value"),
  start = purrr::map_chr(funding, "start-date.year.value"),
  end = purrr::map_chr(funding, "end-date.year.value")) %>% 
  mutate(timeframe = glue::glue("{start} - {end}")) %>% 
  select(type, funder, title, timeframe) 
funding$type <- stringr::str_replace_all(funding$type, "SALARY_AWARD", "SALARY AWARD")
  funding <- funding %>% 
  mutate(Amount = amount)
kable(funding,  col.names = c("Type", "Funder", "Title", "Duration", "Amount")) %>%
    column_spec(1, width = "5em") %>% 
    column_spec(2, width = "12em") %>% 
  column_spec(3, width = "20em") %>% 
    kable_styling(bootstrap_options = "hover") 
```


```{r}
results <- my.orcid(params$orcid.id) # single
```



```{r}
papers  <-  my.filter(results, max.authors=params$max.authors, order=params$order,
                   journal.only=params$journal.only, years.since=params$years.since,
                   spacer=params$spacer, bold.author = params$bold.author)
```

## Publications 
<br>
```{r list.papers, results='asis'}
print_papers(papers)
```


